[0m14:13:32.788568 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d39b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10878b7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10878b2e0>]}


============================== 14:13:32.801531 | b44dba10-4bf7-4c47-8cde-e44012aafffb ==============================
[0m14:13:32.801531 [info ] [MainThread]: Running with dbt=1.7.13
[0m14:13:32.801946 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/waragonp/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init jaffle_shop', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:13:32.802558 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/waragonp/.dbt')}
[0m14:13:32.802863 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:13:32.803577 [debug] [MainThread]: Starter project path: /Users/waragonp/dbt-playground/.venv/lib/python3.10/site-packages/dbt/include/starter_project
[0m14:13:32.807094 [info ] [MainThread]: 
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:13:32.807367 [info ] [MainThread]: Setting up your profile.
[0m14:13:32.807764 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m14:13:32.808816 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.039131083, "process_user_time": 1.223969, "process_kernel_time": 0.094406, "process_mem_max_rss": "105971712", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:13:32.809229 [debug] [MainThread]: Command `dbt init` failed at 14:13:32.809137 after 0.04 seconds
[0m14:13:32.809486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d39b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108854bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108854d30>]}
[0m14:13:32.809756 [debug] [MainThread]: Flushing usage events
[0m14:41:34.276541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10358db40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b6b9a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b6add0>]}


============================== 14:41:34.280604 | a1b83bd4-85ad-458c-85e3-10665601567e ==============================
[0m14:41:34.280604 [info ] [MainThread]: Running with dbt=1.7.13
[0m14:41:34.281043 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/waragonp/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:41:34.281801 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/waragonp/dbt-playground/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:41:34.284162 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0218115, "process_user_time": 1.203359, "process_kernel_time": 0.114734, "process_mem_max_rss": "98025472", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:41:34.284630 [debug] [MainThread]: Command `dbt run` failed at 14:41:34.284526 after 0.02 seconds
[0m14:41:34.285096 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10358db40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b6bbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b6b9a0>]}
[0m14:41:34.285449 [debug] [MainThread]: Flushing usage events
